config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope :corp do
    devise_for :corporate_users
  end

  namespace :corp do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :users, only: [:index, :show]
    resources :corporate_users, only: [:index]
    namespace :items do
      resources :uploads, only: [:new, :create]
    end
    namespace :users do
      resources :uploads, only: [:new, :create]
    end
    namespace :corporate_users do
      resources :uploads, only: [:new, :create]
    end
  end

  root "users#show"

  get    "/users/sign_in",  to: "users/sessions#new"
  post   "/users/sign_in",  to: "users/sessions#create"
  delete "/users/sign_out", to: "users/sessions#destroy"

  resources :users, only: [:show]
  resources :items, only: [:index]
  resources :lendings, only: [:new, :create, :edit, :update]
end

app/models/item_type.rb
# frozen_string_literal: true

class ItemType < ApplicationRecord
  has_many :item_basic_infos, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/corp/corporate_controller_base.rb
# frozen_string_literal: true

class Corp::CorporateControllerBase < ApplicationController
  before_action :redirect_if_guest

  private

  def redirect_if_guest
    redirect_to new_corporate_user_session_path unless current_corporate_user
  end
end

app/controllers/corp/corporate_users/uploads_controller.rb
# frozen_string_literal: true

class Corp::CorporateUsers::UploadsController < Corp::CorporateControllerBase
  def new; end

  def create
    params = upload_params
    file = params[:csv]
    overwrite = params[:overwrite] == '1'

    unless file.content_type.include?('text/csv')
      flash[:danger] = I18n.t('flash.corp.corporate_users_uploads.invalid_mime')
      redirect_to new_corp_corporate_users_upload_path
      return
    end

    begin
      upload_result = Corp::UploadCorporateUsersCsvUseCase.new.execute(file.open, overwrite)
    rescue => e
      flash[:danger] = e.message
      redirect_to new_corp_corporate_users_upload_path
      return
    end

    message = I18n.t('flash.corp.corporate_users_uploads.success', success_count: upload_result.success_count)
    if upload_result.skip_count > 0
      message += I18n.t('flash.corp.corporate_users_uploads.skip', skip_count: upload_result.skip_count)
    end
    flash[:success] = message
    redirect_to new_corp_corporate_users_upload_path
  end

  private

  def upload_params
    params.require(:upload).permit(:csv, :overwrite)
  end
end

app/controllers/corp/corporate_users_controller.rb
# frozen_string_literal: true

class Corp::CorporateUsersController < Corp::CorporateControllerBase
  def index
    @users = CorporateUser.order(id: :asc)
    if params[:s].present?
      name_query = '%' + params[:s] + '%'
      @users = @users.where('corporate_users.first_name LIKE ? OR ' +
                              'corporate_users.middle_name LIKE ? OR ' +
                              'corporate_users.last_name LIKE ?',
                            name_query, name_query, name_query)
    end
    @users = @users.page(params[:page])
  end
end

app/controllers/corp/items/uploads_controller.rb
# frozen_string_literal: true

class Corp::Items::UploadsController < Corp::CorporateControllerBase
  def new; end

  def create
    params = upload_params
    file = params[:csv]
    overwrite = params[:overwrite] == '1'

    unless file.content_type.include?('text/csv')
      flash[:danger] = I18n.t('flash.corp.items_uploads.invalid_mime')
      redirect_to new_corp_items_upload_path
      return
    end

    begin
      upload_result = Corp::UploadItemsCsvUseCase.new.execute(file.open, overwrite)
    rescue => e
      flash[:danger] = e.message
      redirect_to new_corp_items_upload_path
      return
    end

    message = I18n.t('flash.corp.items_uploads.success', success_count: upload_result.success_count)
    if upload_result.skip_count > 0
      message += I18n.t('flash.corp.items_uploads.skip', skip_count: upload_result.skip_count)
    end
    flash[:success] = message
    redirect_to new_corp_items_upload_path
  end

  private

  def upload_params
    params.require(:upload).permit(:csv, :overwrite)
  end
end

app/controllers/corp/items_controller.rb
# frozen_string_literal: true

class Corp::ItemsController < Corp::CorporateControllerBase
  def index
    @items = ItemBasicInfo.eager_load(:item_type, :lent_histories)
                          .order(created_at: :asc)
    @items = @items.where('item_basic_infos.name LIKE ?', '%' + params[:s] + '%') if params[:s].present?
    @items = @items.where(item_type_id: params[:type].to_i) if params[:type].present? && params[:type].to_i.positive?
    @items = @items.page(params[:page])
  end

  def show
    @item = ItemBasicInfo.find_by(id: params[:id])

    unless @item
      flash[:danger] = I18n.t('flash.corp.items.not_found', id: params[:id])
      redirect_to corp_items_path
    end
  end

  def new
    @item = ItemBasicInfo.new(count: 0)
  end

  def edit
    @item = ItemBasicInfo.find_by(id: params[:id])

    unless @item
      flash[:danger] = I18n.t('flash.corp.items.not_found', id: params[:id])
      redirect_to corp_items_path
    end
  end

  def create
    @item = ItemBasicInfo.new(item_params)
    unless @item.save
      render 'new', status: :unprocessable_entity
      return
    end

    redirect_to corp_items_path
  end

  def update
    @item = ItemBasicInfo.find(params[:id])
    @item.count = @item.tags = nil
    @item.assign_attributes(item_params)
    unless @item.save
      render 'edit', status: :unprocessable_entity
      return
    end

    redirect_to corp_items_path(@item.id)
  end

  private

  # Strong Parameter を生成する
  # @return [ActionController::Parameters]
  def item_params
    result = params.require(:item)
                   .permit(:name, :item_type_id, :status, :count_type, :count, :tags, :max_lent_period, :is_extendable)
    result.delete(:count_type)
    result[:status] = result[:status].to_i
    result[:tags] = result[:tags].split("\n").filter(&:present?) if result[:tags]
    if result[:max_lent_period]
      result[:max_lent_period] = ItemBasicInfo.convert_max_lent_period(result[:max_lent_period])
    end
    result
  end
end

app/controllers/corp/users/uploads_controller.rb
# frozen_string_literal: true

class Corp::Users::UploadsController < Corp::CorporateControllerBase
  def new; end

  def create
    params = upload_params
    file = params[:csv]
    overwrite = params[:overwrite] == '1'

    unless file.content_type.include?('text/csv')
      flash[:danger] = I18n.t('flash.corp.users_uploads.invalid_mime')
      redirect_to new_corp_users_upload_path
      return
    end

    begin
      upload_result = Corp::UploadUsersCsvUseCase.new.execute(file.open, overwrite)
    rescue => e
      flash[:danger] = e.message
      redirect_to new_corp_users_upload_path
      return
    end

    message = I18n.t('flash.corp.users_uploads.success', success_count: upload_result.success_count)
    if upload_result.skip_count > 0
      message += I18n.t('flash.corp.users_uploads.skip', skip_count: upload_result.skip_count)
    end
    flash[:success] = message
    redirect_to new_corp_users_upload_path
  end

  private

  def upload_params
    params.require(:upload).permit(:csv, :overwrite)
  end
end

app/controllers/corp/users_controller.rb
# frozen_string_literal: true

class Corp::UsersController < Corp::CorporateControllerBase
  def index
    @users = User.order(id: :asc)
    if params[:s].present?
      name_query = '%' + params[:s] + '%'
      @users = @users.where('users.first_name LIKE ? OR users.middle_name LIKE ? OR users.last_name LIKE ?',
                            name_query, name_query, name_query)
    end
    @users = @users.page(params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])

    unless @user
      flash[:danger] = I18n.t('flash.corp.users.not_found', id: params[:id])
      redirect_to corp_users_path
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < UserControllerBase
  def index
    @items = ItemBasicInfo.eager_load(:item_type, :lent_histories)
                          .order(created_at: :asc)
    @items = @items.where('item_basic_infos.name LIKE ?', '%' + params[:s] + '%') if params[:s].present?
    @items = @items.where(item_type_id: params[:type].to_i) if params[:type].present? && params[:type].to_i.positive?
    @items = @items.page(params[:page])
  end
end

app/helpers/corp/corporate_users/uploads_helper.rb
# frozen_string_literal: true

module Corp::CorporateUsers::UploadsHelper
end

app/helpers/corp/corporate_users_helper.rb
# frozen_string_literal: true

module Corp::CorporateUsersHelper
end

app/helpers/corp/items/uploads_helper.rb
# frozen_string_literal: true

module Corp::Items::UploadsHelper
end

app/helpers/corp/items_helper.rb
# frozen_string_literal: true

module Corp::ItemsHelper
end

app/helpers/corp/users/uploads_helper.rb
# frozen_string_literal: true

module Corp::Users::UploadsHelper
end

app/helpers/corp/users_helper.rb
# frozen_string_literal: true

module Corp::UsersHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/corp/items/_form.html.erb
<% if is_edit %>
  <% target_url = "/corp/items/#{@item.id}" %>
  <% method = :patch %>
<% else %>
  <% target_url = '/corp/items' %>
  <% method = :post %>
<% end %>

<%= form_with(url: target_url, scope: 'item', method:) do |form| %>
  <% if @item.errors.any? %>
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :name, I18n.t('activerecord.attributes.item_basic_info.name') %>
    <%= form.text_field :name, value: @item.name, disabled: is_edit %>
  </div>
  <div>
    <%= form.label :item_type_id, I18n.t('activerecord.attributes.item_basic_info.item_type') %>
    <%= form.select :item_type_id, ItemType.all.map { |type| [type.name, type.id.to_s] }, selected: @item.item_type_id %>
  </div>
  <div>
    <%= form.label :status, I18n.t('activerecord.attributes.item_basic_info.status') %>
    <%= form.select :status, ItemBasicInfo.statuses, {}, { selected: @item.status } %>
  </div>
  <div>
    <%= form.radio_button :count_type, :count %>
    <%= form.label :count_type_count, I18n.t('views.corp.items._form.count_type_count') %>
  </div>
  <div>
    <%= form.label :count, I18n.t('activerecord.attributes.item_basic_info.count') %>
    <%= form.number_field :count, min: 0, value: @item.count || 1 %>
  </div>
  <div>
    <%= form.radio_button :count_type, :tags %>
    <%= form.label :count_type_tags, I18n.t('views.corp.items._form.count_type_tag') %>
  </div>
  <div>
    <%= form.label :tags, I18n.t('activerecord.attributes.item_basic_info.tags') %>
    <%= form.text_area :tags, value: @item.tags&.join("\n") %>
  </div>
  <div>
    <%= form.label :max_lent_period, I18n.t('activerecord.attributes.item_basic_info.max_lent_period') %>
    <%= form.text_field :max_lent_period, value: @item.max_lent_period_as_string, placeholder: 'YYYY/MM/DD', pattern: /\d{1,4}\/(0?[0-9]|1[0-2])\/([0-2]?[0-9]|3[01])/ %>
  </div>
  <div>
    <%= form.label :is_extendable, I18n.t('activerecord.attributes.item_basic_info.is_extendable') %>
    <%= form.check_box :is_extendable, checked: @item.is_extendable %>
  </div>
  <%= form.submit (is_edit ? I18n.t('views.corp.items._form.submit_edit') : I18n.t('views.corp.items._form.submit_new')), class: 'btn btn-primary', name: nil %>
<% end %>

<script>
  const radioAsCount = document.getElementById('item_count_type_count');
  const radioAsTags = document.getElementById('item_count_type_tags');
  const inputCount = document.getElementById('item_count');
  const inputTags = document.getElementById('item_tags');

  radioAsCount.addEventListener('change', () => {
      refleshEnabledStatus();
  });
  radioAsTags.addEventListener('change', () => {
      refleshEnabledStatus();
  });

  function refleshEnabledStatus() {
      inputCount.disabled = !radioAsCount.checked;
      inputTags.disabled = !radioAsTags.checked;
  }

  function initForm() {
      let hasCount = <%= !!@item.count %>;
      if (hasCount) {
          radioAsCount.checked = true;
      }
      else {
          radioAsTags.checked = true;
      }
      refleshEnabledStatus();
  }
  initForm();
</script>

app/views/corp/items/edit.html.erb
<h3>物品情報更新</h3>
<%= render 'form', is_edit: true %>

app/views/corp/items/index.html.erb
<div class="container">
  <div class="row justify-content-between">
    <h3 class="col-md-7"><%= I18n.t('views.corp.items.index.title') %></h3>
    <div class="col-md-1" style="padding-top: 25px">
      <%= button_to I18n.t('views.corp.items.index.import'), new_corp_items_upload_path, method: :get, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-1" style="padding-top: 25px; padding-left: 50px">
      <%= button_to I18n.t('views.corp.items.index.new'), new_corp_item_path, method: :get, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<div>
  <%= form_with(url: '/corp/items', method: 'get') do |form| %>
    <%= form.label :s, I18n.t('views.corp.items.index.form.s-label') %>
    <%= form.text_field :s, value: params[:s] %>
    <%= form.label :type, I18n.t('views.corp.items.index.form.type-label') %>
    <% types = [%w[--- 0]].concat(ItemType.order(id: :asc).map { |type| [type.name, type.id.to_s] }) %>
    <%= form.select :type, types, selected: types.find { |v| v[1] == params[:type] } || '---' %>
    <%= form.submit I18n.t('views.corp.items.index.form.submit'), class: 'btn btn-primary', name: nil %>
  <% end %>
</div>
<div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= I18n.t('views.corp.items.index.table_header.type') %></th>
        <th scope="col"><%= I18n.t('views.corp.items.index.table_header.name') %></th>
        <th scope="col"><%= I18n.t('views.corp.items.index.table_header.stocks') %></th>
        <th scope="col"><%= I18n.t('views.corp.items.index.table_header.total_count') %></th>
      </tr>
    </thead>
    <% @items.each do |current| %>
      <tr>
        <td><%= current.item_type.name %></td>
        <td><%= link_to current.name, corp_item_path(current.id) %></td>
        <% total_count = current.count || current.tags.length %>
        <td><%= total_count - current.lent_histories.in_lent.count %></td>
        <td><%= total_count %></td>
      </tr>
    <% end %>
  </table>

  <%= paginate @items %>
</div>

app/views/corp/items/new.html.erb
<h3>物品登録</h3>
<%= render 'form', is_edit: false %>

app/views/corp/items/show.html.erb
<div class="text-center">
  <h2><%= I18n.t('views.corp.items.show.title') %></h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-7"></div>
    <div class="col-md-1">
      <%= button_to I18n.t('views.corp.items.show.button-return'), corp_items_path, method: :get, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-1">
      <%= button_to I18n.t('views.corp.items.show.button-edit'), edit_corp_item_path(@item.id), method: :get, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<h3><%= I18n.t('views.corp.items.show.basic-info.title') %></h3>
<table class="table">
  <tr>
    <th><%= I18n.t('views.corp.items.show.basic-info.header.key') %></th>
    <th><%= I18n.t('views.corp.items.show.basic-info.header.value') %></th>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.id') %></td>
    <td><%= @item.id %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.item_type') %></td>
    <td><%= @item.item_type.name %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.name') %></td>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.max_lent_period') %></td>
    <td><%= @item.max_lent_period_as_string || I18n.t('views.corp.items.show.basic-info.none') %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.is_extendable') %></td>
    <td><%= @item.is_extendable %></td>
  </tr>
  <% total_count = @item.count || @item.tags.length %>
  <tr>
    <td><%= I18n.t('views.corp.items.show.basic-info.stocks') %></td>
    <td><%= total_count - @item.lent_histories.in_lent.count %></td>
  </tr>
  <tr>
    <td><%= I18n.t('views.corp.items.show.basic-info.total_count') %></td>
    <td><%= total_count %></td>
  </tr>
  <% if @item.tags %>
    <tr>
      <td><%= I18n.t('views.corp.items.show.basic-info.tags') %></td>
      <td>
        <% @item.tags.each do |tag| %>
          <div><%= tag %></div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<h3><%= I18n.t('views.corp.items.show.histories.title') %></h3>
<% if @item.lent_histories.any? %>
  <table class="table">
    <tr>
      <th><%= I18n.t('activerecord.attributes.lent_history.user_id') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.user') %></th>
      <% if @item.tags %>
        <th><%= I18n.t('activerecord.attributes.lent_history.tag') %></th>
      <% end %>
      <th><%= I18n.t('activerecord.attributes.lent_history.lent_at') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.period') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.returned_at') %></th>
    </tr>
    <% @item.lent_histories.order(created_at: :desc).each do |history| %>
      <tr>
        <td><%= history.user_id %></td>
        <td><%= history.user.full_name %></td>
        <% if @item.tags %>
          <td><%= history.tag %></td>
        <% end %>
        <td><%= history.lent_at %></td>
        <td><%= history.period %></td>
        <td><%= history.returned_at || I18n.t('views.corp.items.show.histories.no_returned') %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <b><%= I18n.t('views.corp.items.show.histories.none') %></b>
<% end %>