config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope :corp do
    devise_for :corporate_users
  end

  namespace :corp do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :users, only: [:index, :show]
    resources :corporate_users, only: [:index]
    namespace :items do
      resources :uploads, only: [:new, :create]
    end
    namespace :users do
      resources :uploads, only: [:new, :create]
    end
    namespace :corporate_users do
      resources :uploads, only: [:new, :create]
    end
  end

  root "users#show"

  get    "/users/sign_in",  to: "users/sessions#new"
  post   "/users/sign_in",  to: "users/sessions#create"
  delete "/users/sign_out", to: "users/sessions#destroy"

  resources :users, only: [:show]
  resources :items, only: [:index]
  resources :lendings, only: [:new, :create, :edit, :update]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :lent_histories, dependent: :destroy

  validates :first_name, presence: true
  validates :middle_name, presence: true, allow_nil: true
  validates :last_name, presence: true
  validates :employee_id, presence: true, uniqueness: true
  validates :department, presence: true
  validates :email, email_format: { message: I18n.t('errors.messages.email_format') }, presence: true, uniqueness: true
  validates :slack_channel, presence: true, allow_nil: true

  # フルネームを取得する
  # @return [String] 姓 [ミドルネーム ]名
  def full_name
    middle_name.nil? ? "#{last_name} #{first_name}" : "#{last_name} #{middle_name} #{first_name}"
  end
end

app/controllers/corp/users/uploads_controller.rb
# frozen_string_literal: true

class Corp::Users::UploadsController < Corp::CorporateControllerBase
  def new; end

  def create
    params = upload_params
    file = params[:csv]
    overwrite = params[:overwrite] == '1'

    unless file.content_type.include?('text/csv')
      flash[:danger] = I18n.t('flash.corp.users_uploads.invalid_mime')
      redirect_to new_corp_users_upload_path
      return
    end

    begin
      upload_result = Corp::UploadUsersCsvUseCase.new.execute(file.open, overwrite)
    rescue => e
      flash[:danger] = e.message
      redirect_to new_corp_users_upload_path
      return
    end

    message = I18n.t('flash.corp.users_uploads.success', success_count: upload_result.success_count)
    if upload_result.skip_count > 0
      message += I18n.t('flash.corp.users_uploads.skip', skip_count: upload_result.skip_count)
    end
    flash[:success] = message
    redirect_to new_corp_users_upload_path
  end

  private

  def upload_params
    params.require(:upload).permit(:csv, :overwrite)
  end
end

app/controllers/corp/users_controller.rb
# frozen_string_literal: true

class Corp::UsersController < Corp::CorporateControllerBase
  def index
    @users = User.order(id: :asc)
    if params[:s].present?
      name_query = '%' + params[:s] + '%'
      @users = @users.where('users.first_name LIKE ? OR users.middle_name LIKE ? OR users.last_name LIKE ?',
                            name_query, name_query, name_query)
    end
    @users = @users.page(params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])

    unless @user
      flash[:danger] = I18n.t('flash.corp.users.not_found', id: params[:id])
      redirect_to corp_users_path
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < ApplicationController
  include Users::SessionsHelper
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # rubocop:disable Rails/I18nLocaleTexts
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to users_sign_in_url, status: :see_other
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < UserControllerBase
  def show
    @lent_histories = @user.lent_histories.order(returned_at: :desc)
    @lent_histories = @lent_histories.in_lent if params[:lent_status].present? && params[:lent_status].to_i == 1
    @lent_histories = @lent_histories.not_in_lent if params[:lent_status].present? && params[:lent_status].to_i == 2
    @lent_histories = @lent_histories.page(params[:page])
  end
end

app/helpers/corp/users/uploads_helper.rb
# frozen_string_literal: true

module Corp::Users::UploadsHelper
end

app/helpers/corp/users_helper.rb
# frozen_string_literal: true

module Corp::UsersHelper
end

app/helpers/users/sessions_helper.rb
# frozen_string_literal: true

module Users::SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    reset_session
    @current_user = nil  # rubocop:disable Rails/HelperInstanceVariable
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/show.html.erb
<div>
    <h1>あなたの貸出状況</h1>
</div>

<div>
  <%= form_with(url: user_path(@user), method: 'get') do |form| %>
    <%= form.label :lent_status, I18n.t('views.users.status') %>
    <% types = [["貸出中", 1], ["返却済み", 2]] %>
    <%= form.select :lent_status, types, include_blank: "選択して下さい", selected: params[:lent_status] %>
    <%= form.submit I18n.t('views.corp.items.index.form.submit'), class: 'btn btn-primary', name: nil %>
  <% end %>
</div>

<div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= I18n.t('activerecord.attributes.item_basic_info.item_type') %></th>
        <th scope="col"><%= I18n.t('activerecord.attributes.item_basic_info.name') %></th>
        <th scope="col"><%= I18n.t('activerecord.attributes.lent_history.tag') %></th>
        <th scope="col"><%= I18n.t('activerecord.attributes.lent_history.lent_at') %></th>
        <th scope="col"><%= I18n.t('activerecord.attributes.lent_history.period') %></th>
        <th scope="col"><%= I18n.t('activerecord.attributes.lent_history.returned_at') %></th>
        <th scope="col"><%= I18n.t('views.users.extension') %></th>
        <th scope="col"><%= I18n.t('views.users.return') %></th>
      </tr>
    </thead>
    <% @lent_histories.each do |current| %>
      <tr>
        <td><%= current.item_basic_info.item_type.name %></td>
        <td><%= current.item_basic_info.name %></td>
        <td><%= current.tag %></td>
        <td><%= current.lent_at.strftime("%F") %></td>
        <td><%= current.period.strftime("%F") %></td>
        <td><%= current.returned_at.present? ? current.returned_at.strftime("%F") : '' %></td>
        <% if !current.returned_at and current.item_basic_info.is_extendable %>
        <td><%= button_to I18n.t('views.users.button-extension'), edit_lending_path(current), method: :get %></td>
        <% end %>
        <% if !current.returned_at %>
        <td><%= button_to I18n.t('views.users.button-return'), lending_path(current), method: :patch, params: { returned_at: Time.current } %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <%= paginate @lent_histories %>
</div>