config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope :corp do
    devise_for :corporate_users
  end

  namespace :corp do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :users, only: [:index, :show]
    resources :corporate_users, only: [:index]
    namespace :items do
      resources :uploads, only: [:new, :create]
    end
    namespace :users do
      resources :uploads, only: [:new, :create]
    end
    namespace :corporate_users do
      resources :uploads, only: [:new, :create]
    end
  end

  root "users#show"

  get    "/users/sign_in",  to: "users/sessions#new"
  post   "/users/sign_in",  to: "users/sessions#create"
  delete "/users/sign_out", to: "users/sessions#destroy"

  resources :users, only: [:show]
  resources :items, only: [:index]
  resources :lendings, only: [:new, :create, :edit, :update]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :lent_histories, dependent: :destroy

  validates :first_name, presence: true
  validates :middle_name, presence: true, allow_nil: true
  validates :last_name, presence: true
  validates :employee_id, presence: true, uniqueness: true
  validates :department, presence: true
  validates :email, email_format: { message: I18n.t('errors.messages.email_format') }, presence: true, uniqueness: true
  validates :slack_channel, presence: true, allow_nil: true

  # フルネームを取得する
  # @return [String] 姓 [ミドルネーム ]名
  def full_name
    middle_name.nil? ? "#{last_name} #{first_name}" : "#{last_name} #{middle_name} #{first_name}"
  end
end

app/controllers/corp/corporate_controller_base.rb
# frozen_string_literal: true

class Corp::CorporateControllerBase < ApplicationController
  before_action :redirect_if_guest

  private

  def redirect_if_guest
    redirect_to new_corporate_user_session_path unless current_corporate_user
  end
end

app/controllers/corp/corporate_users/uploads_controller.rb
# frozen_string_literal: true

class Corp::CorporateUsers::UploadsController < Corp::CorporateControllerBase
  def new; end

  def create
    params = upload_params
    file = params[:csv]
    overwrite = params[:overwrite] == '1'

    unless file.content_type.include?('text/csv')
      flash[:danger] = I18n.t('flash.corp.corporate_users_uploads.invalid_mime')
      redirect_to new_corp_corporate_users_upload_path
      return
    end

    begin
      upload_result = Corp::UploadCorporateUsersCsvUseCase.new.execute(file.open, overwrite)
    rescue => e
      flash[:danger] = e.message
      redirect_to new_corp_corporate_users_upload_path
      return
    end

    message = I18n.t('flash.corp.corporate_users_uploads.success', success_count: upload_result.success_count)
    if upload_result.skip_count > 0
      message += I18n.t('flash.corp.corporate_users_uploads.skip', skip_count: upload_result.skip_count)
    end
    flash[:success] = message
    redirect_to new_corp_corporate_users_upload_path
  end

  private

  def upload_params
    params.require(:upload).permit(:csv, :overwrite)
  end
end

app/controllers/corp/corporate_users_controller.rb
# frozen_string_literal: true

class Corp::CorporateUsersController < Corp::CorporateControllerBase
  def index
    @users = CorporateUser.order(id: :asc)
    if params[:s].present?
      name_query = '%' + params[:s] + '%'
      @users = @users.where('corporate_users.first_name LIKE ? OR ' +
                              'corporate_users.middle_name LIKE ? OR ' +
                              'corporate_users.last_name LIKE ?',
                            name_query, name_query, name_query)
    end
    @users = @users.page(params[:page])
  end
end

app/controllers/corp/items/uploads_controller.rb
# frozen_string_literal: true

class Corp::Items::UploadsController < Corp::CorporateControllerBase
  def new; end

  def create
    params = upload_params
    file = params[:csv]
    overwrite = params[:overwrite] == '1'

    unless file.content_type.include?('text/csv')
      flash[:danger] = I18n.t('flash.corp.items_uploads.invalid_mime')
      redirect_to new_corp_items_upload_path
      return
    end

    begin
      upload_result = Corp::UploadItemsCsvUseCase.new.execute(file.open, overwrite)
    rescue => e
      flash[:danger] = e.message
      redirect_to new_corp_items_upload_path
      return
    end

    message = I18n.t('flash.corp.items_uploads.success', success_count: upload_result.success_count)
    if upload_result.skip_count > 0
      message += I18n.t('flash.corp.items_uploads.skip', skip_count: upload_result.skip_count)
    end
    flash[:success] = message
    redirect_to new_corp_items_upload_path
  end

  private

  def upload_params
    params.require(:upload).permit(:csv, :overwrite)
  end
end

app/controllers/corp/items_controller.rb
# frozen_string_literal: true

class Corp::ItemsController < Corp::CorporateControllerBase
  def index
    @items = ItemBasicInfo.eager_load(:item_type, :lent_histories)
                          .order(created_at: :asc)
    @items = @items.where('item_basic_infos.name LIKE ?', '%' + params[:s] + '%') if params[:s].present?
    @items = @items.where(item_type_id: params[:type].to_i) if params[:type].present? && params[:type].to_i.positive?
    @items = @items.page(params[:page])
  end

  def show
    @item = ItemBasicInfo.find_by(id: params[:id])

    unless @item
      flash[:danger] = I18n.t('flash.corp.items.not_found', id: params[:id])
      redirect_to corp_items_path
    end
  end

  def new
    @item = ItemBasicInfo.new(count: 0)
  end

  def edit
    @item = ItemBasicInfo.find_by(id: params[:id])

    unless @item
      flash[:danger] = I18n.t('flash.corp.items.not_found', id: params[:id])
      redirect_to corp_items_path
    end
  end

  def create
    @item = ItemBasicInfo.new(item_params)
    unless @item.save
      render 'new', status: :unprocessable_entity
      return
    end

    redirect_to corp_items_path
  end

  def update
    @item = ItemBasicInfo.find(params[:id])
    @item.count = @item.tags = nil
    @item.assign_attributes(item_params)
    unless @item.save
      render 'edit', status: :unprocessable_entity
      return
    end

    redirect_to corp_items_path(@item.id)
  end

  private

  # Strong Parameter を生成する
  # @return [ActionController::Parameters]
  def item_params
    result = params.require(:item)
                   .permit(:name, :item_type_id, :status, :count_type, :count, :tags, :max_lent_period, :is_extendable)
    result.delete(:count_type)
    result[:status] = result[:status].to_i
    result[:tags] = result[:tags].split("\n").filter(&:present?) if result[:tags]
    if result[:max_lent_period]
      result[:max_lent_period] = ItemBasicInfo.convert_max_lent_period(result[:max_lent_period])
    end
    result
  end
end

app/controllers/corp/users/uploads_controller.rb
# frozen_string_literal: true

class Corp::Users::UploadsController < Corp::CorporateControllerBase
  def new; end

  def create
    params = upload_params
    file = params[:csv]
    overwrite = params[:overwrite] == '1'

    unless file.content_type.include?('text/csv')
      flash[:danger] = I18n.t('flash.corp.users_uploads.invalid_mime')
      redirect_to new_corp_users_upload_path
      return
    end

    begin
      upload_result = Corp::UploadUsersCsvUseCase.new.execute(file.open, overwrite)
    rescue => e
      flash[:danger] = e.message
      redirect_to new_corp_users_upload_path
      return
    end

    message = I18n.t('flash.corp.users_uploads.success', success_count: upload_result.success_count)
    if upload_result.skip_count > 0
      message += I18n.t('flash.corp.users_uploads.skip', skip_count: upload_result.skip_count)
    end
    flash[:success] = message
    redirect_to new_corp_users_upload_path
  end

  private

  def upload_params
    params.require(:upload).permit(:csv, :overwrite)
  end
end

app/controllers/corp/users_controller.rb
# frozen_string_literal: true

class Corp::UsersController < Corp::CorporateControllerBase
  def index
    @users = User.order(id: :asc)
    if params[:s].present?
      name_query = '%' + params[:s] + '%'
      @users = @users.where('users.first_name LIKE ? OR users.middle_name LIKE ? OR users.last_name LIKE ?',
                            name_query, name_query, name_query)
    end
    @users = @users.page(params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])

    unless @user
      flash[:danger] = I18n.t('flash.corp.users.not_found', id: params[:id])
      redirect_to corp_users_path
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < ApplicationController
  include Users::SessionsHelper
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # rubocop:disable Rails/I18nLocaleTexts
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to users_sign_in_url, status: :see_other
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < UserControllerBase
  def show
    @lent_histories = @user.lent_histories.order(returned_at: :desc)
    @lent_histories = @lent_histories.in_lent if params[:lent_status].present? && params[:lent_status].to_i == 1
    @lent_histories = @lent_histories.not_in_lent if params[:lent_status].present? && params[:lent_status].to_i == 2
    @lent_histories = @lent_histories.page(params[:page])
  end
end

app/helpers/corp/corporate_users/uploads_helper.rb
# frozen_string_literal: true

module Corp::CorporateUsers::UploadsHelper
end

app/helpers/corp/corporate_users_helper.rb
# frozen_string_literal: true

module Corp::CorporateUsersHelper
end

app/helpers/corp/items/uploads_helper.rb
# frozen_string_literal: true

module Corp::Items::UploadsHelper
end

app/helpers/corp/items_helper.rb
# frozen_string_literal: true

module Corp::ItemsHelper
end

app/helpers/corp/users/uploads_helper.rb
# frozen_string_literal: true

module Corp::Users::UploadsHelper
end

app/helpers/corp/users_helper.rb
# frozen_string_literal: true

module Corp::UsersHelper
end

app/helpers/users/sessions_helper.rb
# frozen_string_literal: true

module Users::SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    reset_session
    @current_user = nil  # rubocop:disable Rails/HelperInstanceVariable
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/corp/users/index.html.erb
<div>
  <% flash.each do |type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{type}") %>
  <% end %>
</div>
<div class="container">
  <div class="row justify-content-between">
    <h3 class="col-md-8"><%= I18n.t('views.corp.users.index.title') %></h3>
    <div class="col-md-1" style="padding-top: 25px">
      <%= button_to I18n.t('views.corp.users.index.import'), new_corp_users_upload_path, method: :get, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<div>
  <%= form_with(url: '/corp/users', method: 'get') do |form| %>
    <%= form.label :s, I18n.t('views.corp.users.index.form.s-label') %>
    <%= form.text_field :s, value: params[:s] %>
    <%= form.submit I18n.t('views.corp.users.index.form.submit'), class: 'btn btn-primary', name: nil %>
  <% end %>
</div>
<div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= I18n.t('views.corp.users.index.table_header.name') %></th>
        <th scope="col"><%= I18n.t('views.corp.users.index.table_header.employee_id') %></th>
        <th scope="col"><%= I18n.t('views.corp.users.index.table_header.department') %></th>
        <th scope="col"><%= I18n.t('views.corp.users.index.table_header.email') %></th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, corp_user_path(user.id) %></td>
        <td><%= user.employee_id %></td>
        <td><%= user.department %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </table>

  <%= paginate @users %>
</div>

app/views/corp/users/show.html.erb
<div class="text-center">
  <h2><%= I18n.t('views.corp.users.show.title') %></h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-1">
      <%= button_to I18n.t('views.corp.users.show.button-return'), corp_users_path, method: :get, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<h3><%= I18n.t('views.corp.users.show.basic-info.title') %></h3>
<table class="table">
  <tr>
    <th><%= I18n.t('views.corp.users.show.basic-info.header.key') %></th>
    <th><%= I18n.t('views.corp.users.show.basic-info.header.value') %></th>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.user.id') %></td>
    <td><%= @user.id %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.user.employee_id') %></td>
    <td><%= @user.employee_id %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.user.name') %></td>
    <td><%= @user.full_name %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.user.department') %></td>
    <td><%= @user.department %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.user.email') %></td>
    <td><%= @user.email %></td>
  </tr>
</table>

<h3><%= I18n.t('views.corp.users.show.histories.title') %></h3>
<% if @user.lent_histories.any? %>
  <table class="table">
    <tr>
      <th><%= I18n.t('activerecord.attributes.lent_history.item_basic_info_id') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.item_basic_info') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.tag') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.lent_at') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.period') %></th>
      <th><%= I18n.t('activerecord.attributes.lent_history.returned_at') %></th>
    </tr>
    <% @user.lent_histories.order(created_at: :desc).each do |history| %>
      <tr>
        <td><%= history.item_basic_info_id %></td>
        <td><%= history.item_basic_info.name %></td>
        <td><%= history.tag %></td>
        <td><%= history.lent_at %></td>
        <td><%= history.period %></td>
        <td><%= history.returned_at || I18n.t('views.corp.users.show.histories.no_returned') %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <b><%= I18n.t('views.corp.users.show.histories.none') %></b>
<% end %>