config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope :corp do
    devise_for :corporate_users
  end

  namespace :corp do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :users, only: [:index, :show]
    resources :corporate_users, only: [:index]
    namespace :items do
      resources :uploads, only: [:new, :create]
    end
    namespace :users do
      resources :uploads, only: [:new, :create]
    end
    namespace :corporate_users do
      resources :uploads, only: [:new, :create]
    end
  end

  root "users#show"

  get    "/users/sign_in",  to: "users/sessions#new"
  post   "/users/sign_in",  to: "users/sessions#create"
  delete "/users/sign_out", to: "users/sessions#destroy"

  resources :users, only: [:show]
  resources :items, only: [:index]
  resources :lendings, only: [:new, :create, :edit, :update]
end

app/controllers/lendings_controller.rb
# frozen_string_literal: true

class LendingsController < UserControllerBase
  before_action :now_item

  def new; end

  def edit
    @lent_history = LentHistory.find_by(id: params[:id])
  end

  def create
    @lent_history = if params[:tag]
                      LentHistory.new(user_id: @user.id, item_basic_info_id: @item.id, tag: params[:tag],
                                      lent_at: Time.current, period: params[:period])
                    else
                      LentHistory.new(user_id: @user.id, item_basic_info_id: @item.id, lent_at: Time.current,
                                      period: params[:period])
                    end
    if @lent_history.save
      flash[:success] = I18n.t('success.messages.lend')
      redirect_to root_url
    else
      flash.now[:danger] = I18n.t('success.messages.not-lend')
      render 'lendings/new', status: :unprocessable_entity
    end
  end

  def update
    @lent_history = LentHistory.find_by(id: params[:id])
    if params[:period]
      @lent_history.update(period: params[:period])
      flash[:success] = I18n.t('success.messages.extension')
      redirect_to root_url
    elsif params[:returned_at]
      @lent_history.update(returned_at: params[:returned_at])
      flash[:success] = I18n.t('success.messages.return')
      redirect_to root_url
    end
  end

  private

  def now_item
    @item = ItemBasicInfo.find_by(id: params[:item_id]) if params[:item_id]
  end
end

app/helpers/lendings_helper.rb
# frozen_string_literal: true

module LendingsHelper
end

app/views/lendings/edit.html.erb
<div class="col">
      <%= button_to I18n.t('views.lendings.button-return'), root_path, method: :get, class: 'btn btn-primary' %>
</div>

<div>
    <h1>延長する</h1>
</div>

<table class="table">
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.name') %></td>
    <td><%= @lent_history.item_basic_info.name %></td>
  </tr>
  <% if @lent_history.tag %>
  <tr>
    <td><%= I18n.t('activerecord.attributes.lent_history.tag') %></td>
    <td><%= @lent_history.tag %></td>
  </tr>
  <% end %>
  <tr>
    <td><%= I18n.t('views.lendings.period') %></td>
    <td><%= @lent_history.period %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.max_lent_period') %></td>
    <td><%= @lent_history.item_basic_info.max_lent_period_as_string || I18n.t('views.corp.items.show.basic-info.none') %></td>
  </tr>
</table>

<div>
  <%= form_with url: lending_path(@lent_history), method: 'patch' do |form| %>
    <%= form.label :period, I18n.t('views.lendings.period') %>
    <%= form.date_field :period, min: Time.current %>
    <%= form.submit I18n.t('views.lendings.button-extension'), class: 'btn btn-primary', name: nil %>
  <% end %>
</div>

app/views/lendings/new.html.erb
<div class="col">
      <%= button_to I18n.t('views.lendings.button-return'), items_path, method: :get, class: 'btn btn-primary' %>
</div>

<div>
    <h1>借りる</h1>
</div>

<table class="table">
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.name') %></td>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <td><%= I18n.t('activerecord.attributes.item_basic_info.max_lent_period') %></td>
    <td><%= @item.max_lent_period_as_string || I18n.t('views.corp.items.show.basic-info.none') %></td>
  </tr>
  <% total_count = @item.count || @item.tags.length %>
  <tr>
    <td><%= I18n.t('views.corp.items.show.basic-info.stocks') %></td>
    <td><%= total_count - @item.lent_histories.in_lent.count %></td>
  </tr>
</table>

<div>
  <% if @item.tags %>
    <% lent_histories_with_tags = @item.lent_histories.in_lent %>
    <% now_lent_tags = lent_histories_with_tags.pluck(:tag) %>
    <% item_tags = @item.tags - now_lent_tags %>
    <%= form_with url: lendings_path, method: 'post' do |form| %>
      <%= hidden_field_tag :item_id, @item.id %> 
      <%= form.label :tag, I18n.t('views.lendings.tag') %>
      <% types = item_tags.map { |type| [type, type] } %>
      <%= form.select :tag, types, include_blank: "選択して下さい" %>
      <%= form.label :period, I18n.t('views.lendings.period') %>
      <%= form.date_field :period, min: Time.current %>
      <%= form.submit I18n.t('views.lendings.lend'), class: 'btn btn-primary', name: nil %>
    <% end %>
  <% else %>
    <%= form_with url: lendings_path, method: 'post' do |form| %>
      <%= hidden_field_tag :item_id, @item.id %>
      <%= form.label :period, I18n.t('views.lendings.period') %>
      <% options = { min: Time.current.to_date } %>
      <% options[:max] = (Time.current + @item.max_lent_period).to_date if @item.max_lent_period.present? %>
      <%= form.date_field :period, options %>
      <%= form.submit I18n.t('views.lendings.lend'), class: 'btn btn-primary', name: nil %>
    <% end %>
  <% end %>


</div>